version: '3.5'

services:
  automatic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automatic
    restart: always
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0', '1']
              capabilities: [gpu]
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./models:/src/stable-diffusion-webui/models/Stable-diffusion:rw,cached
      - ./lora:/src/stable-diffusion-webui/models/Lora:rw,cached
      - ./output:/src/stable-diffusion-webui/outputs:rw,cached
    networks:
      - automatic

networks:
  automatic:
    driver: bridge
